### PR TITLE
Add robots.txt and sitemap

### PR DESCRIPTION
**Pull request by ajdapretnar**
Try one more time.

### CODE REVIEW

**Comment by ajdapretnar** [comment]
N-th attempt done. See if it works @irgolic. 🤞

**Comment by irgolic** [comment]
👏
Screenshot 2020-04-20 at 16 12 56
Merging this after @NejcHirci submits PR removing /tags and /categories.

**Comment by ajdapretnar** [comment]
I still don't understand what these `xhtml:link` tags do, but it doesn't work without them, so... 🤷

**Comment by irgolic** [comment]
@ajdapretnar Can you rebase?

**Comment by ajdapretnar** [comment]
What for? It doesn't say it needs rebasing... 😮

**Comment by irgolic** [comment]
For the sitemap to regenerate.

**Pull request merged**
